### ISSUE TITLE
エラー ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):

### ISSUE THREAD

**Issue by takuya178** [takuya178/healthy-combi#124]
# 質問内容
画像をブラウザからs3へ直接アップロードする機能追加後、dbに保存することができず以下のエラーが発生する。このエラーを解決したいです。

```
ActiveSupport::MessageVerifier::InvalidSignature (ActiveSupport::MessageVerifier::InvalidSignature):
```
[![Image from Gyazo](https://i.gyazo.com/8a1a62d4efce8a6a1a690d7f1125f894.jpg)](https://gyazo.com/8a1a62d4efce8a6a1a690d7f1125f894)

<br>
<br>

# 実装内容
画像をブラウザから直接アップロードするため以下の記事を参考。ブラウザから画像をs3へ直接アップロードすることはできました。
[Rails での S3 への画像の直接アップロード](https://devcenter.heroku.com/ja/articles/direct-to-s3-image-uploads-in-rails)
[S3に直接画像をアップロードする（Ruby on Rails）](https://qiita.com/DaichiSaito/items/80e89f0c96d88afcc5ff)

<br>
以下はcontrollerでbinding.pryをかけて、オブジェクトにimageデータが入っているか確認しています。

<br>

**mains_controller.rb**

```ruby
before_action :set_s3_direct_post, only: [:new, :create] 

 def new
    @main_sub_form = MainSubForm.new
    @mains = Main.find_by(name: params[:name])
  end

  def create
    @main_sub_form = MainSubForm.new(main_sub_form_params)
     binding.pry
    @main_sub_form.save
  end

private

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end
```

```ruby
pry(#<MainsController>)> @main_sub_form
=> #<MainSubForm:0x00007f8fef3710c8
@image="//healthy-combi.s3.ap-northeast-1.amazonaws.com/uploads/1a029b57-ca26-4412-9f4a-f24f09556de3/A5E1CD9A-A124-4524-8AE8-799BE0FF0DE0.jpeg",
.
.
.>
```

その後、@main_sub_form.saveのところでエラーが発生しています。

```
ActiveSupport::MessageVerifier::InvalidSignature: ActiveSupport::MessageVerifier::InvalidSignature
from /Users/conve_recipe/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.4/lib/active_support/message_verifier.rb:176:in `verify'
```

<br>

ブラウザからs3に直接アップロードする前は、添付した画像ファイルをdbに保存していました。以下がその内容です。（ここでエラーは発生せず正常に保存されます。）

```ruby
[1] pry(#<MainsController>)> @main_sub_form 
=> #<MainSubForm:0x00007f8fec0dd3f0
 @image="eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBY2M9IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b645da192c3f933ae1850bf8f5e7d33af4b87267",
.
.
.>

```

<br>
<br>

# 現状の理解内容
ActiveSupport::MessageVerifier::InvalidSignatureについて以下の記事を参考に調べました。
[ActiveSupport::MessageVerifier < Object
](https://api.rubyonrails.org/v6.1.4/classes/ActiveSupport/MessageVerifier.html)
MessageVerifierは、改ざんを防ぐために署名されたメッセージを簡単に生成・検証することができる。
さらにmessage_verifier.rb内のverify(*args, **options)はメッセージが同じシークレットで署名されていなかったり、Base64エンコードされていなかったりすると、InvalidSignatureを発生させます。との記載がありました。

**lib/active_support/message_verifier.rb**

```ruby
    def verify(*args, **options)
      verified(*args, **options) || raise(InvalidSignature)
    end
```

以上のことから、imageのデータがbase64エンコードされていないのでエラーが発生していると考えています。

```ruby
pry(#<MainsController>)> @main_sub_form
=> #<MainSubForm:0x00007f8fef3710c8
@image="//healthy-combi.s3.ap-northeast-1.amazonaws.com/uploads/1a029b57-ca26-4412-9f4a-f24f09556de3/A5E1CD9A-A124-4524-8AE8-799BE0FF0DE0.jpeg",
// ここがエンコードされたらエラーがなくなるのでは？
```

active-storage-base64というgemがあったのですが、rails6.1以上の対応だったので断念しました。
[active-storage-base64](https://github.com/rootstrap/active-storage-base64#installation)
他に方法があればご教授いただけると幸いです。

**Comment by MrFuku** [comment]
> ブラウザからs3に直接アップロードする前は、添付した画像ファイルをdbに保存していました。以下がその内容です。（ここでエラーは発生せず正常に保存されます。）

ファイル保存用のカラムに文字列を保存しようとしているからじゃないですか？

**Comment by takuya178** [comment]
@MrFuku 

**schema.rb**
```ruby
  create_table "mains", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4", force: :cascade do |t|
    t.string "image"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end
```

imageはstringで保存していました。
これをtext型に変更すれば保存できるのでしょうか？

**Comment by yuji91** [comment]
ActiveStorageを使っているので`attach`メソッドを使わないとオブジェクトの画像用のカラムに登録できないと思います。
https://railsguides.jp/active_storage_overview.html

**Comment by yuji91** [comment]
面談でもお伝えしましたが`ActiveSupport::MessageVerifier::InvalidSignature`については以下の記事を参考にしてください。
https://note.com/marikooota/n/n7ac0a66e34ea

一旦ローカルのファイルでattachメソッドの成功まで確認できたので、引き続きS3のファイルでどう対応するかを対応頂ければと思います。

**Comment by takuya178** [comment]
[](url)
